CREATE TABLE [dbo].[Questions]
(
	[ID] INT NOT NULL IDENTITY(1,1) PRIMARY KEY, 
    [Title] VARCHAR(250) NOT NULL, 
    [Answer] VARCHAR(MAX) NOT NULL,
	[OwnerUserID] INT NOT NULL,
	[ShortName] VARCHAR(100) NOT NULL,
	[Time] DATETIME NOT NULL DEFAULT GETDATE(),
	[Views] INT NOT NULL DEFAULT 0
)